# Degree Days {#sec-degree-days}

A common application of weather and climate data is predicting phenological events like egg laying for insects, or fruit ripening for tree crops. These predictions are possible due to research which has modeled the relationship between phenology and accumulated heat, or degree days.

The researchers who study the relationship between phenology and accumulated heat use several calculations to measure degree days. Many of the most common degree day formulas can be found in the `degday` R package.

<https://ucanr-igis.github.io/degday/>

All you need after that are the phenology tables.

Example: https://ucanr-igis.shinyapps.io/noworm/

## Which one to use?

If you're using published phenology tables or a degree day model, use the same method as the author used.

If you're a researcher, note:

    "Since no advantages were noted in the more complicated double
    and corrected methods, the single triangle and single sine
    methods are preferred since they are less complicated
    procedures." 
    (Roltsch et al 1999)
    summarized at <https://ipm.ucanr.edu/WEATHER/ddeval.html>


*More coming soon...*

