project:
  type: book
  output-dir: docs

book:
  title: "AgroClimate Community Cookbook"
  author: "Andy Lyons, Chloe Faehndrich"
  date: "1/31/2024"
  chapters:
    - index.qmd
    - 01_data-wrangling.qmd
    - 02_weather-data.qmd
    - 03_agroclimate-metrics.qmd
    - 04_degday-chill.qmd
    - 05_agroclimate-rasters.qmd
    - 06_modeled-climate-data.qmd
    - 07_climate-analogues.qmd
    - 99_other.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # will add support for epub and pdf when it is a little more developed
  # pdf:
  #   documentclass: scrreprt

editor: source

