project:
  type: book
  #output-dir: docs
  output-dir: "docs/0.2"

comments:
  hypothesis:
    theme: clean
    openSidebar: true

book:
  title: "AgroClimate Cookbook"
  subtitle: "Code recipes for working with weather-driven agricultural metrics"
  editor:
   - Andy Lyons
  contributor:
   - Chloe Faehndrich
  date: "2/10/2024"
  cover-image: "cover.png"
  chapters:
    - index.qmd
    - 01_data-wrangling.qmd
    - 02_weather-data.qmd
    - 03_simple-agroclim-metrics.qmd
    - 04_degday.qmd
    - 05_chill.qmd
    - 06_agroclimate-rasters.qmd
    - 07_modeled-climate-data.qmd
    - 08_climate-analogues.qmd
    - 99_other.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
    toc-depth: 4
    toc-expand: 4
    link-external-icon: true
    link-external-newwindow: true
  # We will add support for epub and pdf when it is a little more developed
  # pdf:
  #   documentclass: scrreprt


editor: source

